config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :friends, only: [:index, :new, :edit, :update, :create, :show, :destroy] do
    resources :bookings, only: [:create, :edit, :update] do
      resources :reviews, only: [:new, :create]
    end
  end
  resources :reviews, only: [:destroy]
  resources :bookings, only: [:destroy]
  resources :dashboard, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :friend
  has_one :review, dependent: :destroy
  validates :activity, :start_date, :end_date, presence: true

  STATUS = %w[Pending Confirmed Finished Canceled].freeze
  validates :booking_status, presence: true

  def start_date_before_end_date
    return if start_date.blank? || end_date.blank?

    if end_date < start_date
      errors.add(:end_date, "The end date can not be before the start date")
    end
  end
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  validates :start_date, :end_date, :interests,
  :activity, :location, :bio, :first_name, :last_name, presence: true
  validates :age, presence: true, numericality: { only_integer: true, greater_than: 18 }
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0 }
  has_one_attached :image

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :friend
  belongs_to :booking
  validates :title, :body, :rating, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_one :review, dependent: :destroy
  has_one :friend
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :birth_date])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :birth_date])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  def index
    @bookings = policy_scope(Booking)
  end

  def create
    @booking = Booking.new(bookings_param)
    @friend = Friend.find(params[:friend_id])
    @booking.friend = @friend
    @booking.user = current_user
    @booking.activity = @friend.activity
    @booking.booking_status = "Pending"
    @booking.num_of_days = (Date.parse(params[:booking]["end_date"]) - Date.parse(params[:booking]["start_date"])).to_i
    authorize @booking

    if @booking.num_of_days > 0 && @booking.save
      redirect_to dashboard_index_path, notice: "Booking successfully created"
    else
      if @booking.num_of_days <= 0
        redirect_to friend_path(@friend), alert: "You can't choose a date before the start date"
      else
        redirect_to friend_path(@friend), status: :unprocessable_entity
      end
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    @friend = Friend.find(params[:friend_id])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.num_of_days = (Date.parse(params[:booking]["end_date"]) - Date.parse(params[:booking]["start_date"])).to_i unless params[:booking]["end_date"].nil?
    @booking.update(bookings_param)
    authorize @booking

    redirect_to dashboard_index_path, notice: "Booking successfully updated"
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    authorize @booking

    redirect_to dashboard_index_path, notice: "Booking successfully deleted"
  end

  private


  def bookings_param
    params.require(:booking).permit(:activity, :start_date, :end_date, :num_of_days, :booking_status)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @bookings = policy_scope(Booking.where(user: current_user))
    @friend = Friend.where(user: current_user).first
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!
  def index
    @friends = policy_scope(Friend)
    @markers = @friends.geocoded.map do |friend|
      {
        lat: friend.latitude,
        lng: friend.longitude
      }
    end
  end

  def show
    @friend = Friend.find(params[:id])
    @booking = Booking.new
    @review = Review.new
    @reviews = Review.where(friend: params[:id]).order(created_at: :desc)
    @avg = (@reviews.map { |review| review.rating }.sum / @reviews.length).to_i unless @reviews.empty?
    @review.friend = @friend
    @review.booking = @booking
    authorize @friend
  end

  def edit
    @friend = Friend.find(params[:id])
    authorize @friend
  end

  def new
    @friend = Friend.new
    authorize @friend
  end

  def update
    @friend = Friend.find(params[:id])
    @friend.update(friends_param)
    authorize @friend
    redirect_to friend_path(@friend), notice: "Friend updated successfully"
  end

  def create
    @friend = Friend.new(friends_param)
    @friend.user = current_user

    authorize @friend

    if @friend.save
      redirect_to friend_path(@friend), notice: "Friend created successfully"
    else
      render :new, status: :unprocessable_entity, alert: "Could not create a friend"
    end
  end

  def destroy
    @friend = Friend.find(params[:id])
    @friend.destroy

    authorize @friend
    redirect_to friends_path, notice: "Friend deleted successfully"
  end

  private

  def friends_param
    params.require(:friend).permit(:interests, :first_name, :last_name, :image, :age, :bio, :location, :price, :activity, :start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @friend = Friend.where(user: current_user).first
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  def new
    @friend = Friend.find(params[:friend_id])
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
    @review.friend = @friend
    @review.booking = @booking
    authorize @review
  end

  def create
    @friend = Friend.find(params[:friend_id])
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.friend = @friend
    @review.booking = @booking
    @review.user = current_user
    authorize @review

    if @review.save
      redirect_to friend_path(@friend), notice: "Review successfully created"
    else
      render :new, status: :unprocessable_entity, alert: "Could not create a review"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to friend_path(@review.friend), notice: "Review successfully deleted"
    authorize @review
  end

  private

  def review_params
    params.require(:review).permit(:title, :body, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="flex min-h-full flex-col items-center justify-center px-6 py-12 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <h2 class="mt-12 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Booking now! 🎉</h2>
  </div>
  <div class="mt-6 sm:mx-auto sm:w-full sm:max-w-sm">
    <%= simple_form_for [@friend, @booking], data: { controller: 'flatpickr' } do |f| %>
  <div class="mt-2">
  <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startTime", class: "block w-full rounded-md border-0 py-2 px-3 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-1 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" } }  %>
  </div>
  <div class="mt-2">
  <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endTime", class: "block w-full rounded-md border-0 py-2 px-3 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-1 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" } } %>
  </div>

  <%= f.button :submit, "Book me!", class:"btn btn-primary px-6 py-3 bg-light-purple text-azure-white w-full rounded-md mb-2 hover:bg-dark-purple transition-colors duration-300" %>
<% end %>
</div>

app/views/bookings/index.html.erb
<div class="container mt-3">
  <h1>My Bookings</h1>

  <% @bookings.each do |booking| %>
    <p>Friend: <%= booking.friend.last_name %></p>
    <p>Activity:<%= booking.friend.activity %></p>
    <p>Start date:<%= booking.start_date %></p>
    <p>End Date:<%= booking.end_date %></p>
    <p>Number of days: <%= booking.num_of_days %></p>
    <p>Price: $<%= booking.friend.price * booking.num_of_days %></p>
    <% if policy(booking).edit? %>
      <%= link_to "Edit booking", edit_friend_booking_path(booking.friend, booking), class: "btn btn-primary text-white" %>
    <% end %>
    <% if policy(booking).destroy? %>
      <%= link_to "Delete the booking", booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "you sure?"}, method: :delete, class: "btn btn-danger text-white" %>
    <% end %>
    <%= link_to "Add a review", new_friend_booking_review_path(booking.friend, booking), class:"btn btn-info" %>
    <hr>
  <% end %>
</div>

app/views/dashboard/index.html.erb
<% if @bookings.any? %>
  <div class="bg-white">
    <div class="py-16 sm:py-24">
      <div class="max-w-7xl mx-auto sm:px-2 lg:px-8">
        <div class="max-w-2xl mx-auto px-4 lg:max-w-4xl lg:px-0">
          <h1 class="text-2xl font-extrabold tracking-tight text-gray-900 sm:text-3xl">Bookings history</h1>
          <p class="mt-2 text-sm text-gray-500">Check the status of recent bookings, manage returns, and discover similar products.</p>
        </div>
      </div>

      <div class="mt-16">
        <h2 class="sr-only">Recent bookings</h2>
        <div class="max-w-7xl mx-auto sm:px-2 lg:px-8">
          <div class="max-w-2xl mx-auto space-y-8 sm:px-4 lg:max-w-4xl lg:px-0">
                  <% @bookings.each do |booking| %>
            <div class="bg-white border-t border-b border-gray-200 shadow-sm sm:rounded-lg sm:border">

                <div class="flex items-center p-4 border-b border-gray-200 sm:p-6 sm:grid sm:grid-cols-4 sm:gap-x-6">
                <dl class="flex-1 grid grid-cols-5 gap-x-6 text-sm sm:col-span-5 sm:grid-cols-5 lg:col-span-5">

                  <div class="hidden sm:block">
                    <dt class="font-medium text-gray-900">Date placed</dt>
                    <dd class="mt-1 text-gray-500">
                    <%= booking.created_at.strftime(" %d %b %Y") %>
                    </dd>
                  </div>
                  <div>
                    <dt class="font-medium text-gray-900">Total amount</dt>
                    <dd class="mt-1 font-medium text-gray-900">$<%= booking.friend.price * booking.num_of_days %></dd>

                  </div>
                  <div>
                    <dt class="font-medium text-gray-900">Total days</dt>
                    <dd class="mt-1 font-medium text-gray-900"><%= booking.num_of_days %></dd>

                  </div>
                  <div>
                    <dt class="font-medium text-gray-900">From:</dt>
                    <dd class="mt-1 font-medium text-gray-900"><%= booking.start_date.strftime(" %d %b %Y") %></dd>

                  </div>
                  <div>
                    <dt class="font-medium text-gray-900">To:</dt>
                    <dd class="mt-1 font-medium text-gray-900"><%= booking.end_date.strftime(" %d %b %Y") %></dd>

                  </div>
                </dl>




              </div>

              <!-- Products -->
              <ul role="list" class="divide-y divide-gray-200">
                <li class="p-4 sm:p-6">
                  <div class="flex items-center sm:items-start">
                    <div class="flex-shrink-0 w-20 h-20 bg-gray-200 rounded-lg overflow-hidden sm:w-40 sm:h-40">
                      <%= cl_image_tag booking.friend.image.key, class: "w-full h-full object-center object-cover" %>

                    </div>
                    <div class="flex-1 ml-6 text-sm">
                      <div class="font-medium text-gray-900 sm:flex sm:justify-between">
                        <h5><%= booking.friend.first_name %> <%= booking.friend.last_name %></h5>
                        <p class="mt-2 sm:mt-0">$<%= booking.friend.price %>/ day</p>
                      </div>
                      <p class="hidden text-gray-500 sm:block sm:mt-2"><%= booking.friend.bio %></p>
                    </div>
                  </div>

                  <div class="mt-6 sm:flex sm:justify-between">
                    <div class="flex items-center">
                      <!-- Heroicon name: solid/check-circle -->
                      <% if booking.booking_status == "Pending" %>
                        <i class="far fa-hourglass" style="color: #627500;"></i>
                        <p class="ml-2 text-sm font-medium text-gray-500"><%= booking.booking_status %></p>
                      <% elsif booking.booking_status == "Confirmed" %>

                      <i class="fas fa-check" style="color: #00ff11;"></i>
                      <p class="ml-2 text-sm font-medium text-gray-500"><%= booking.booking_status %></p>
                      <% elsif booking.booking_status == "Finished" %>

                    <i class="far fa-calendar-check" style="color: #005eff;"></i>
                      <p class="ml-2 text-sm font-medium text-gray-500"><%= booking.booking_status %></p>
                      <% elsif booking.booking_status == "Canceled" %>

                      <i class="fas fa-ban" style="color: #ff0000;"></i>
                      <p class="ml-2 text-sm font-medium text-gray-500"><%= booking.booking_status %></p>
                      <% end %>
                    </div>

                    <div class="mt-6 border-t border-gray-200 pt-4 flex items-center space-x-4 divide-x divide-gray-200 text-sm font-medium sm:mt-0 sm:ml-4 sm:border-none sm:pt-0">
                      <div class="flex-1 flex justify-center">
                      <%= link_to "View profile", friend_path(booking.friend), class: "text-indigo-600 whitespace-nowrap hover:text-indigo-500" %>
                      </div>
                    <% if policy(booking).edit? %>
                        <div class="flex-1 pl-4 flex justify-center">
                            <%= link_to "Edit booking", edit_friend_booking_path(booking.friend, booking), class: "text-indigo-600 whitespace-nowrap hover:text-indigo-500" %>
                        </div>
                      <% end %>
                      <% if policy(booking).destroy? %>
                      <div class="flex-1 pl-4 flex justify-center">
                        <%= link_to "Delete the booking", booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "you sure?"}, method: :delete, class: "text-indigo-600 whitespace-nowrap hover:text-indigo-500" %>
                      </div>
                      <% end %>
                      <div class="flex-1 pl-4 flex justify-center">
                        <%= link_to "Add a review", new_friend_booking_review_path(booking.friend, booking), class:"text-indigo-600 whitespace-nowrap hover:text-indigo-500" %>
                      </div>

                    </div>
                  </div>
                </li>

                <!-- More products... -->
              </ul>
            </div>
            <% end %>

          </div>

            <!-- More bookings... -->
        </div>
      </div>
    </div>
  </div>
  <% else %>
  <div class="max-w-7xl mx-auto py-16 sm:py-24">
      <div class="max-w-2xl mx-auto px-4 lg:max-w-4xl lg:px-0">
        <h1 class="text-2xl font-extrabold tracking-tight text-gray-900 sm:text-3xl">Sorry no bookings found</h1>
      </div>
    </div>
<% end %>

<% unless @friend.nil? %>
  <div class="bg-white">
    <div class="py-16 sm:py-24">
      <div class="max-w-7xl mx-auto sm:px-2 lg:px-8">
        <div class="max-w-2xl mx-auto px-4 lg:max-w-4xl lg:px-0">
          <h1 class="text-2xl font-extrabold tracking-tight text-gray-900 sm:text-3xl">Profile bookings</h1>
          <p class="mt-2 text-sm text-gray-500">Check the status of recent profiles, manage returns, and discover similar products.</p>
        </div>
      </div>

      <div class="mt-16">
        <h2 class="sr-only">Profile bookings</h2>
        <div class="max-w-7xl mx-auto sm:px-2 lg:px-8">
          <div class="max-w-2xl mx-auto space-y-8 sm:px-4 lg:max-w-4xl lg:px-0">
          <% @friend.bookings.each do |booking| %>
            <div class="bg-white border-t border-b border-gray-200 shadow-sm sm:rounded-lg sm:border">

              <div class="flex items-center p-4 border-b border-gray-200 sm:p-6 sm:grid sm:grid-cols-4 sm:gap-x-6">
                <dl class="flex-1 grid grid-cols-5 gap-x-6 text-sm sm:col-span-5 sm:grid-cols-5 lg:col-span-5">

                  <div class="hidden sm:block">
                    <dt class="font-medium text-gray-900">Date placed</dt>
                    <dd class="mt-1 text-gray-500">
                    <%= booking.created_at.strftime(" %d %b %Y") %>
                    </dd>
                  </div>
                  <div>
                    <dt class="font-medium text-gray-900">Total amount</dt>
                    <dd class="mt-1 font-medium text-gray-900">$<%= booking.friend.price * booking.num_of_days %></dd>

                  </div>
                  <div>
                    <dt class="font-medium text-gray-900">Total days</dt>
                    <dd class="mt-1 font-medium text-gray-900"><%= booking.num_of_days %></dd>

                  </div>
                  <div>
                    <dt class="font-medium text-gray-900">From:</dt>
                    <dd class="mt-1 font-medium text-gray-900"><%= booking.start_date.strftime(" %d %b %Y") %></dd>

                  </div>
                  <div>
                    <dt class="font-medium text-gray-900">To:</dt>
                    <dd class="mt-1 font-medium text-gray-900"><%= booking.end_date.strftime(" %d %b %Y") %></dd>

                  </div>
                </dl>




              </div>

              <!-- Products -->
              <ul role="list" class="divide-y divide-gray-200">
                <li class="p-4 sm:p-6">
                  <div class="flex items-center sm:items-start">

                    <div class="flex-1 text-sm">
                      <div class="font-medium text-gray-900 sm:flex sm:justify-between">
                        <h5> <strong> <%= booking.user.first_name %> <%= booking.user.last_name %></strong></h5>
                        <p class="mt-2 sm:mt-0">$<%= @friend.price %>/ day</p>
                      </div>
                      <p class="hidden text-gray-500 sm:block sm:mt-2"><%= booking.user.email %></p>
                    </div>
                  </div>

                  <div class="mt-6 sm:flex sm:justify-between">
                    <div class="flex items-center">
                      <%= simple_form_for [booking.friend, booking], data: { controller: 'autosave', autosave_delay_value: '1000'} do |f| %>

                        <%= f.input :booking_status, collection: Booking::STATUS, selected: booking.booking_status || Booking::STATUS.first, input_html: { data: { action: 'change->autosave#save' } } %>

                      <% end %>
                      </div>

                    <div class="mt-6 border-t border-gray-200 pt-4 flex items-center space-x-4 divide-x divide-gray-200 text-sm font-medium sm:mt-0 sm:ml-4 sm:border-none sm:pt-0">
                      <div class="flex-1 flex justify-center">
                      <%= link_to "View profile", friend_path(@friend), class: "text-indigo-600 whitespace-nowrap hover:text-indigo-500" %>
                      </div>
                    <%# %>

                    </div>
                  </div>
                </li>

                <!-- More products... -->
              </ul>
            </div>
            <!-- More bookings... -->
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% else %>
  <div class="max-w-7xl mx-auto py-16 sm:py-24">
      <div class="max-w-2xl mx-auto px-4 lg:max-w-4xl lg:px-0">
        <h1 class="text-2xl font-extrabold tracking-tight text-gray-900 sm:text-3xl">You didn't receive any bookings yet...</h1>
      </div>
  </div>
<% end %>

app/views/friends/new.html.erb
<%= render 'form', friend: @friend %>

app/views/shared/_navbar.html.erb
<nav class="fixed top-0 z-50 bg-light-purple shadow-lg w-full">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative">
    <div class="flex justify-between h-16">
      <div class="flex">
        <div class="-ml-2 mr-2 flex items-center md:hidden">
          <button type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" aria-controls="mobile-menu" aria-expanded="false">
            <span class="sr-only">Open main menu</span>

            <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
            </svg>

            <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <div class="flex-shrink-0 flex items-center">
          <a href="/" class="text-azure-white flex items-center">
             <%= image_tag 'logo/logo.png', class: 'block lg:hidden h-16 w-auto', alt: 'RentAFriend' %>

             <%= image_tag 'logo/logo.png', class: 'hidden lg:block h-16 w-auto', alt: 'RentAFriend' %>

             <h1 class="ml-2 mt-0 font-extrabold text-white">
              <span>RentAFriend</span>
            </h1>
          </a>
        </div>

        <div class="hidden md:ml-6 md:flex md:space-x-8 items-center">
          <%= link_to "Friends", friends_path, class: "text-azure-white hover:bg-dark-purple transation-colors duration-300 px-3 py-2 rounded-md text-sm font-medium" %>
        </div>
      </div>
      <div class="flex items-center">
        <% if user_signed_in? %>
        <% if current_user.friend.nil? %>
        <div class="flex-shrink-0">
        <%= link_to new_friend_path do %>
          <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium hover:bg-dark-purple transation-colors duration-300 hover:border-purple rounded-md text-azure-white shadow-sm  focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple ">
            <!-- Heroicon name: solid/plus-sm -->
            <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd" />
            </svg>
            <span>New friends</span>
          </button>
        <% end %>
        </div>
        <% end %>
        <%# if user signed in %>
        <div class="hidden md:ml-4 md:flex-shrink-0 md:flex md:items-center">

          <button type="button" class="bg-azure-white p-1 rounded-full text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            <span class="sr-only">View notifications</span>
            <!-- Heroicon name: outline/bell -->
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
            </svg>
          </button>

          <!-- Profile dropdown -->
          <div class="ml-3 relative" data-controller="dropdown">
            <div>
              <button type="button" class="rounded-full flex text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" id="user-menu-button" aria-expanded="false" aria-haspopup="true" data-action="dropdown#toggle click@window->dropdown#hide" >

                <span class="sr-only">Open user menu</span>
                <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
              </button>
            </div>

            <div class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-azure-white ring-1 ring-black ring-opacity-5 focus:outline-none hidden " role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1" data-dropdown-target="menu">

              <a href="<%= dashboard_index_path %>" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0">Dashboard</a>
              <a href="<%= edit_user_registration_path %>" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-1">Edit your profile</a>
              <a href="<%= destroy_user_session_path %>" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-2" data-turbo-method="delete">Sign out</a>
            </div>
          </div>
        </div>
        <% else %>
            <%= link_to "Sign in", new_user_session_path, class: "relative inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-azure-white bg-indigo-600 shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 ml-5" %>
        <% end %>
      </div>
    </div>
  </div>


</nav>